resolver: lts-16.22
extra-deps:
  - graphql-0.11.0.0
  - mu-graphql-0.4.1.0
  - mu-persistent-0.3.1.0
  - mu-prometheus-0.4.0.0
  - mu-rpc-0.4.0.1
  - mu-schema-0.3.1.1
  - primitive-extras-0.8
  - primitive-unlifted-0.1.3.0
  - stm-containers-1.1.0.4
  - stm-hamt-1.2.0.4
  - wai-middleware-prometheus-1.0.0
