-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LibraryApi.Object.Book exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import LibraryApi.InputObject
import LibraryApi.Interface
import LibraryApi.Object
import LibraryApi.Scalar
import LibraryApi.ScalarCodecs
import LibraryApi.Union


id : SelectionSet Int LibraryApi.Object.Book
id =
    Object.selectionForField "Int" "id" [] Decode.int


title : SelectionSet String LibraryApi.Object.Book
title =
    Object.selectionForField "String" "title" [] Decode.string


imageUrl : SelectionSet String LibraryApi.Object.Book
imageUrl =
    Object.selectionForField "String" "imageUrl" [] Decode.string


author :
    SelectionSet decodesTo LibraryApi.Object.Author
    -> SelectionSet decodesTo LibraryApi.Object.Book
author object____ =
    Object.selectionForCompositeField "author" [] object____ Basics.identity
