-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module LibraryApi.Mutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import LibraryApi.InputObject
import LibraryApi.Interface
import LibraryApi.Object
import LibraryApi.Scalar
import LibraryApi.ScalarCodecs
import LibraryApi.Union


type alias NewAuthorRequiredArguments =
    { author : LibraryApi.InputObject.NewAuthor }


newAuthor :
    NewAuthorRequiredArguments
    -> SelectionSet decodesTo LibraryApi.Object.Author
    -> SelectionSet decodesTo RootMutation
newAuthor requiredArgs____ object____ =
    Object.selectionForCompositeField "newAuthor" [ Argument.required "author" requiredArgs____.author LibraryApi.InputObject.encodeNewAuthor ] object____ Basics.identity


type alias NewBookRequiredArguments =
    { book : LibraryApi.InputObject.NewBook }


newBook :
    NewBookRequiredArguments
    -> SelectionSet decodesTo LibraryApi.Object.Book
    -> SelectionSet decodesTo RootMutation
newBook requiredArgs____ object____ =
    Object.selectionForCompositeField "newBook" [ Argument.required "book" requiredArgs____.book LibraryApi.InputObject.encodeNewBook ] object____ Basics.identity
