name: Elm CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: npm i
    - name: fetch schema
      run: curl https://raw.githubusercontent.com/higherkindness/mu-haskell/master/examples/library/library.graphql > library.graphql
    - name: Codegen
      run: npm run codegen
    - uses: jorelali/setup-elm@v1
      with:
        elm-version: 0.19.1
    - name: Check that Elm code compiles!
      run: elm make src/Main.elm
