name: Elm CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v8
        with:
          name: 47deg
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - run: nix-build
